#pragma once
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define SPLASH_STATE_SHOW_TIME 3.0
#define SPLASH_SCENE_BACKGROUND_FILEPATH "rsc/UNOb.png"
#define ICON_PATH "rsc/icon.png"
#define MAIN_MENU_BACKGROUND_FILEPATH "rsc/UNO.png"
#define PLAY_BUTTON_FILEPATH "rsc/playbutton.png"
#define PLAY_BUTTON2_FILEPATH "rsc/playbutton2.png"
#define QUIT_BUTTON_FILEPATH "rsc/quitbutton.png"
#define QUIT_BUTTON2_FILEPATH "rsc/quitbutton2.png"
#define GAME_BACKGROUND_FILEPATH "rsc/UNO1.png"
#define GAME_OVER1_BACKGROUND_FILEPATH "rsc/win.png"
#define GAME_OVER2_BACKGROUND_FILEPATH "rsc/lost.png"
#define UNO_BUTTON "rsc/verif_uno.png"
#define CARTE_CACHEE_FILEPATH "rsc/carte_uno.png"
#define ROUGE_FILEPATH "rsc/rouge.png"
#define VERT_FILEPATH "rsc/vert.png"
#define BLEU_FILEPATH "rsc/bleu.png"
#define JAUNE_FILEPATH "rsc/jaune.png"
#define VERT4_FILEPATH "rsc/+4vert.png"
#define ROUGE4_FILEPATH "rsc/+4rouge.png"
#define JAUNE4_FILEPATH "rsc/+4jaune.png"
#define BLEU4_FILEPATH "rsc/+4bleu.png"
#define CHANGEMENT_DE_COULEUR_FILEPATH "rsc/changement_de_couleur.png"
#define PAUSE_BACKGROUND_FILEPATH "rsc/pause.png"
#define ROUGE 0
#define JAUNE 1
#define VERT 2
#define BLEU 3
#define NOIR 4
#define UNO_CARTES_FILEPATH "rsc/cartes_uno.png"
#define BLOQUE 20
#define INVERSE 21
#define DEUX_PLUS 22
#define MODIFIER_COULEUR 50
#define QUATRE_PLUS 51
